"""Initial revision

Revision ID: 766ac9e9fcfe
Revises: 
Create Date: 2024-11-07 19:05:36.545526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766ac9e9fcfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Games',
    sa.Column('GameID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('GameID')
    )
    op.create_table('Users',
    sa.Column('ChatID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TournamentsID', sa.String(), nullable=False),
    sa.Column('Settings', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ChatID')
    )
    op.create_table('Tournaments',
    sa.Column('TournamentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Prize', sa.String(), nullable=False),
    sa.Column('TeamsCount', sa.String(), nullable=False),
    sa.Column('Tier', sa.String(), nullable=False),
    sa.Column('GameID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['GameID'], ['Games.GameID'], ),
    sa.PrimaryKeyConstraint('TournamentID')
    )
    op.create_table('Matches',
    sa.Column('MatchID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TournamentsID', sa.Integer(), nullable=False),
    sa.Column('GamesID', sa.Integer(), nullable=False),
    sa.Column('Time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['GamesID'], ['Games.GameID'], ),
    sa.ForeignKeyConstraint(['TournamentsID'], ['Tournaments.TournamentID'], ),
    sa.PrimaryKeyConstraint('MatchID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_table('Tournaments')
    op.drop_table('Users')
    op.drop_table('Games')
    # ### end Alembic commands ###
